lib/cookoff_web/router.ex
defmodule CookoffWeb.Router do
  use CookoffWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api", CookoffWeb do
    pipe_through :api
    scope "/votes" do
      post "/:entry_id", VoteController, :create
    end
  end

  scope "/", CookoffWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    scope "/competitions" do
      get "/:key/new_entry", EntryController, :new
      post "/:key/new_entry", EntryController, :create
      get "/manage/:competition_private_key/delete_entry/:entry_private_key", EntryController, :delete

      get "/new", CompetitionController, :new
      post "/new", CompetitionController, :create
      get "/update/:key", CompetitionController, :update
      put "/update/:key", CompetitionController, :update_put
      get "/manage/:key", CompetitionController, :manage
      get "/:key", CompetitionController, :public
      get "/:key/results", CompetitionController, :results
    end

    scope "/entries" do
      get "/:key", EntryController, :manage
      put "/:key", EntryController, :update
      get "/delete/:key", EntryController, :withdraw
    end

  end

  # Other scopes may use custom stacks.
  # scope "/api", CookoffWeb do
  #   pipe_through :api
  # end
end

lib/cookoff_web/views/layout_view.ex
defmodule CookoffWeb.LayoutView do
  use CookoffWeb, :view

  def title(conn, assigns, default) do
    try do 
      apply(view_module(conn), :title, [action_name(conn), assigns])
    rescue
      _ ->
        default
    end
  end

end

lib/cookoff_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= title(@conn, assigns, "Food Contest") %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav class="pull-right">
          <%= link "+ Contest", to: competition_path(@conn, :new) %>
        </nav>
        <h1><strong>Food Contest Thing</strong></h1>
        <hr />
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <%= render_existing view_module(@conn), "includes.js", assigns %>
  </body>
</html>

lib/cookoff_web/templates/layout/index.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= title(@conn, assigns, "Food Contest") %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/index.css") %>">
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>