lib/cookoff_web/router.ex
defmodule CookoffWeb.Router do
  use CookoffWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api", CookoffWeb do
    pipe_through :api
    scope "/votes" do
      post "/:entry_id", VoteController, :create
    end
  end

  scope "/", CookoffWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    scope "/competitions" do
      get "/:key/new_entry", EntryController, :new
      post "/:key/new_entry", EntryController, :create
      get "/manage/:competition_private_key/delete_entry/:entry_private_key", EntryController, :delete

      get "/new", CompetitionController, :new
      post "/new", CompetitionController, :create
      get "/update/:key", CompetitionController, :update
      put "/update/:key", CompetitionController, :update_put
      get "/manage/:key", CompetitionController, :manage
      get "/:key", CompetitionController, :public
      get "/:key/results", CompetitionController, :results
    end

    scope "/entries" do
      get "/:key", EntryController, :manage
      put "/:key", EntryController, :update
      get "/delete/:key", EntryController, :withdraw
    end

  end

  # Other scopes may use custom stacks.
  # scope "/api", CookoffWeb do
  #   pipe_through :api
  # end
end

lib/cookoff/competition.ex
defmodule Cookoff.Competition do
  use Ecto.Schema
  import Ecto.Changeset
  alias Cookoff.Competition


  schema "competitions" do
    field :description, :string
    field :facilitator_email, :string
    field :facilitator_first_name, :string
    field :facilitator_last_name, :string
    field :vote_start_time_local, :naive_datetime
    field :vote_end_time_local, :naive_datetime
    field :name, :string
    field :private_key, Ecto.UUID
    field :public_key, Ecto.UUID
    field :vote_end_time_utc, :utc_datetime
    field :vote_start_time_utc, :utc_datetime
    has_many :entries, Cookoff.Entry

    timestamps()
  end

  @doc false
  def changeset(%Competition{} = competition, attrs) do
    competition
    |> cast(attrs, [:name, :private_key, :public_key, :vote_start_time_utc, :vote_end_time_utc, :vote_start_time_local, :vote_end_time_local, :description, :facilitator_first_name, :facilitator_last_name, :facilitator_email])
    |> validate_required([:name, :private_key, :public_key, :vote_start_time_utc, :vote_end_time_utc, :vote_start_time_local, :vote_end_time_local, :facilitator_first_name, :facilitator_last_name, :facilitator_email])
  end
end

lib/cookoff_web/controllers/competition_controller.ex
defmodule CookoffWeb.CompetitionController do
  use CookoffWeb, :controller
  alias Cookoff.{Repo, Competition}
  import Ecto.Query, only: [from: 2]

  plug :valid_uuid, "key" when action in [:public, :manage, :update, :update_put]

  def public(conn, %{"key" => key}) do
    case Competition |> Repo.get_by(public_key: key) |> Repo.preload(:entries) do
      nil -> conn |> put_status(:not_found) |> text("not found")
      competition -> render conn, :public, %{competition: competition}
    end
  end

  def manage(conn, %{"key" => key}) do
    competition = Repo.one from competition in Competition,
      where: competition.private_key == ^key,
      left_join: entries in assoc(competition, :entries),
      left_join: votes in assoc(entries, :votes),
      preload: [entries: {entries, votes: votes}]
    #case Competition |> Repo.get_by(private_key: key) |> Repo.preload(:entries) |> Repo.preload(:votes) do
    case competition do
      nil -> conn |> put_status(:not_found) |> text("not found")
      competition -> render conn, :manage, %{competition: competition}
    end
  end

  def update(conn, %{errors: errors}) do
    render conn, :update, changeset: errors
  end

  def update(conn, %{"key" => key}) do
    case Competition |> Repo.get_by(private_key: key) do
      nil -> conn |> put_status(:not_found) |> text("not found")
      competition -> render conn, :update, changeset: Competition.changeset(competition, %{})
    end
  end

  def update_put(conn, %{"key" => key, "competition" => updated_competition}) do
    updated_competition = updated_competition
    |> Map.update!("vote_start_time_local", fn x -> x <> ":00" end)
    |> Map.update!("vote_end_time_local", fn x -> x <> ":00" end)

    case Competition |> Repo.get_by(private_key: key) do
      nil -> conn |> put_status(:not_found) |> text("not found")
      competition ->
        case Competition.changeset(competition, updated_competition) |> Repo.update do
          {:ok, %{private_key: private_key}} -> redirect conn, to: competition_path(conn, :manage, private_key)
          {:error, reasons} -> update conn, %{errors: reasons}
        end
    end
  end

  def new(conn, %{errors: errors}) do
    render conn, :new, changeset: errors
  end

  def new(conn, _) do
    changeset = Competition.changeset(%Competition{}, %{})
    render conn, :new, changeset: changeset
  end

  def create(conn, %{"competition" => competition}) do
    competition = competition
    |> Map.update!("vote_start_time_local", fn x -> x <> ":00" end)
    |> Map.update!("vote_end_time_local", fn x -> x <> ":00" end)
    |> Map.put("private_key", Ecto.UUID.generate())
    |> Map.put("public_key", Ecto.UUID.generate())

    changeset = Competition.changeset(%Competition{}, competition)

    case Repo.insert changeset do
      {:ok, %{private_key: private_key}} -> redirect conn, to: competition_path(conn, :manage, private_key)
      {:error, reasons} ->
        new conn, %{errors: reasons}
    end
  end

  def results(conn, %{"key" => key}) do
    competition = Repo.one from competition in Competition,
      where: competition.public_key == ^key,
      left_join: entries in assoc(competition, :entries),
      left_join: votes in assoc(entries, :votes),
      preload: [entries: {entries, votes: votes}]
    case competition do
      nil -> conn |> put_status(:not_found) |> text("not found")
      competition -> render conn, :results, competition: competition
    end
  end

  ## PRIVATE PARTS BELOW

  defp valid_uuid(conn, key_name) do
    case conn.params[key_name] |> Ecto.UUID.cast do
      :error -> conn |> put_status(:not_found) |> text("not found") |> halt()
      _ -> conn
    end
  end

end

lib/cookoff_web/views/competition_view.ex
defmodule CookoffWeb.CompetitionView do
  use CookoffWeb, :view

  def format_name(first, last) do
    "#{first} #{last}"
  end

  def current_date_string() do
    date = Ecto.Date.utc() |> Ecto.Date.to_iso8601
    "#{date}T00:00:00"
  end

  def render("includes.js", assigns) do
    competition_path = static_path(assigns.conn, "/js/competition.js")
    raw("<script src=\"#{competition_path}\"></script>")
  end

  def format_datetime(nil), do: ""
  def format_datetime(dt) when is_binary(dt), do: dt |> String.slice(0..15) # remove seconds if string
  def format_datetime(dt) do
    IO.inspect(dt)
    NaiveDateTime.to_iso8601(dt)
    |> String.slice(0..15)
  end

  def title(:manage, assigns), do: "Manage Competition - #{assigns.competition.name}"
  def title(:update, _), do: "Update Competition"
  def title(:new, _), do: "New Competition"
  def title(_, _), do: "Food Contest"

end

lib/cookoff_web/templates/competition/manage.html.eex
<%= link "Modify Competition", to: competition_path(@conn, :update, @competition.private_key), class: "pull-right" %>
<h1><%= @competition.name %></h1>
<p>Description: <%= @competition.description %></h1>
<p>Facilitator Name: <%= format_name(@competition.facilitator_first_name, @competition.facilitator_last_name) %></p>
<p>
  <%= link "Link to public page", to: competition_path(@conn, :public, @competition.public_key) %>
</p>
<p>
  <%= link "Link to management page", to: competition_path(@conn, :manage, @competition.public_key) %>
</p>
<p>Voting starts: <span class="localize-me" data-datetime="<%= @competition.vote_start_time_utc %>"></span></p>
<p>Voting duration:
  <span class="duration-me" data-start-datetime="<%= @competition.vote_start_time_utc %>" data-end-datetime="<%= @competition.vote_end_time_utc %>"</span>
</p>

<%= if (@competition.entries |> Enum.count) > 0 do %>
  <h3>Entries</h3>
  <%= for e <- @competition.entries |> Enum.sort(&(&1.number < &2.number)) do %>
    <div class="list-group-item">
      <span class="pull-right">
        <p>Chef: <strong><%= e.chef_name %></strong></p>
        <%= link "Delete", to: entry_path(@conn, :delete, @competition.private_key, e.private_key) %>
      </span>
      <h4 class="list-group-item-heading">#<%= e.number %> - <%= e.name %></h4>
      <%= link "Management link", to: entry_path(@conn, :manage, e.private_key) %>
      <%= if e.description do %>
        <p class="text-muted"><%= e.description %></p>
      <% end %>
      <%= if e.votes do %>
        <p>Votes: <%= Enum.count(e.votes) %></p>
      <% else %>
        <p>Votes: 0</p>
      <% end %>
    </div>
  <% end %>
<% else %>
  <p>No entries yet</p>
<% end %>

lib/cookoff_web/templates/competition/new.html.eex
<%= form_for @changeset, competition_path(@conn, :create), fn f -> %>

  <div class="form-group">
    <%= label f, :facilitator_first_name, "Your first name" %>
    <%= text_input f, :facilitator_first_name, class: "form-control", placeholder: "John", required: "true" %>
    <%= error_tag f, :facilitator_first_name %>
  </div>

  <div class="form-group">
    <%= label f, :facilitator_last_name, "Your last name" %>
    <%= text_input f, :facilitator_last_name, class: "form-control", placeholder: "Doe", required: "true" %>
    <%= error_tag f, :facilitator_last_name %>
  </div>

  <div class="form-group">
    <%= label f, :facilitator_email, "Your email" %>
    <%= text_input f, :facilitator_email, class: "form-control", placeholder: "john.doe@chefs.com", required: "true" %>
    <%= error_tag f, :facilitator_email %>
  </div>

  <div class="form-group">
    <%= label f, :name, "Contest name" %>
    <%= text_input f, :name, class: "form-control", placeholder: "Chili Cookoff", required: "true" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :description, "Description" %>
    <%= textarea f, :description, class: "form-control", rows: 5%>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= label f, :vote_start_time_local, "Voting Start Time" %>
    <%= text_input f, :vote_start_time_local, class: "form-control convert-utc", type: "datetime-local", data_local_for: "vote-start-time-utc", min: current_date_string(), value: format_datetime(input_value(f, :vote_start_time_local)) %>
    <%= error_tag f, :vote_start_time_local %>
  </div>

  <div class="form-group">
    <%= label f, :vote_end_time_local, "Voting End Time" %>
    <%= text_input f, :vote_end_time_local, class: "form-control convert-utc", type: "datetime-local", data_local_for: "vote-end-time-utc", min: current_date_string(), value: format_datetime(input_value(f, :vote_end_time_local)) %>
    <%= error_tag f, :vote_end_time_local %>
  </div>

  <input type="hidden" name="competition[vote_start_time_utc]" id="vote-start-time-utc" value="<%= input_value(f, :vote_start_time_utc) %>">

  <input type="hidden" name="competition[vote_end_time_utc]" id="vote-end-time-utc" value="<%= input_value(f, :vote_end_time_utc) %>">

  <%= submit "Add", class: "btn btn-primary pull-right" %>
<% end %>

lib/cookoff_web/templates/competition/public.html.eex
<h1><%= @competition.name %></h1>
<p>Description: <%= @competition.description %></h1>
<p>Facilitator Name: <%= format_name(@competition.facilitator_first_name, @competition.facilitator_last_name) %></p>
<p>
  <%= link "Link to public page", to: competition_path(@conn, :public, @competition.public_key) %>
</p>
<p>Voting starts: <span class="localize-me" data-datetime="<%= @competition.vote_start_time_utc %>"></span></p>
<p>Voting duration:
  <span class="duration-me" data-start-datetime="<%= @competition.vote_start_time_utc %>" data-end-datetime="<%= @competition.vote_end_time_utc %>"</span>
</p>
<p>
  <%= link "Add an entry", to: entry_path(@conn, :new, @competition.public_key) %>
</p>

<%= if (@competition.entries |> Enum.count) > 0 do %>
  <h3>Entries</h3>
  <%= for e <- @competition.entries |> Enum.sort(&(&1.number < &2.number)) do %>
    <div class="list-group-item entry-list-item">
      <div class="pull-right">
        <p>Chef: <strong><%= e.chef_name %></strong></p>
      </div>
      <h4 class="list-group-item-heading">#<%= e.number %> - <%= e.name %></h4>
      <button type="button" class="vote btn btn-primary" data-entry-id="<%= e.id %>" data-entry-name="<%= e.name%>">Vote</button>
      <%= if e.description do %>
        <p class="text-muted"><%= e.description %></p>
      <% end %>
    </div>
  <% end %>
<% else %>
  <p>No entries yet</p>
<% end %>


<div class="modal fade" id="vote-modal" tabindex="-1" role="dialog" aria-labelledby="vote-modal-title" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" id="vote-form">
      <div class="modal-header">
        <h3 class="modal-title text-center" id="vote-modal-title">Are you sure this is the chili for you?</h3>
        <a href="#" class="close" data-dismiss="modal">No, cancel!</a>
      </div>
      <div class="modal-body">
        <h3>Show some <span class="font-icon icon-heart-line"></span></h3>
        <br/>
        <label for="voter-name">
          Name (Optional)
        </label>
        <input id="voter-name" type="text" class="form-control" />
        <br/>
        <label for="voter-comments">
          Comments (Optional)
        </label>
        <textarea id="voter-comments" type="text" class="form-control"></textarea>
        <input type="hidden" id="entry-id">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">
          <span>
            Yes, Place Vote!
          </span>
          <small>#<span class="entry-id"></span> <span class="entry-name"></span></small>
        </button>
      </div>
    </div>
    <div class="modal-content text-center" id="confirmation">
      <div class="modal-header">
        <h3 class="modal-title" id="vote-modal-title">Thanks for voting!</h3>
      </div>
      <div class="modal-body">
        <h3>Your vote for #<span class="entry-id"></span> <span class="entry-name"></span> has been added.</h3>
      </div>
    </div>
  </div>
</div>

lib/cookoff_web/templates/competition/results.html.eex
<h1><%= @competition.name %> Results</h1>
<h3>Entries</h3>
<%= for e <- @competition.entries |> Enum.sort(&(&1.number < &2.number)) do %>
  <div class="list-group-item entry-list-item">
    <div class="pull-right">
      <p>Chef: <strong><%= e.chef_name %></strong></p>
    </div>
    <h4 class="list-group-item-heading">#<%= e.number %> - <%= e.name %></h4>
    <button type="button" class="vote btn btn-primary" data-entry-id="<%= e.id %>" data-entry-name="<%= e.name%>">Vote</button>
    <%= if e.description do %>
      <p class="text-muted"><%= e.description %></p>
    <% end %>
  </div>
<% end %>

lib/cookoff_web/templates/competition/update.html.eex
<%= form_for @changeset, competition_path(@conn, :update_put, @changeset.data.private_key), fn f -> %>

  <div class="form-group">
    <%= label f, :facilitator_first_name, "Your first name" %>
    <%= text_input f, :facilitator_first_name, class: "form-control", placeholder: "John", required: "true" %>
    <%= error_tag f, :facilitator_first_name %>
  </div>

  <div class="form-group">
    <%= label f, :facilitator_last_name, "Your last name" %>
    <%= text_input f, :facilitator_last_name, class: "form-control", placeholder: "Doe", required: "true" %>
    <%= error_tag f, :facilitator_last_name %>
  </div>

  <div class="form-group">
    <%= label f, :facilitator_email, "Your email" %>
    <%= text_input f, :facilitator_email, class: "form-control", placeholder: "john.doe@chefs.com", required: "true" %>
    <%= error_tag f, :facilitator_email %>
  </div>

  <div class="form-group">
    <%= label f, :name, "Contest name" %>
    <%= text_input f, :name, class: "form-control", placeholder: "Chili Cookoff", required: "true" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :description, "Description" %>
    <%= textarea f, :description, class: "form-control", rows: 5%>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= label f, :vote_start_time_local, "Voting Start Time" %>
    <%= text_input f, :vote_start_time_local, class: "form-control convert-utc", type: "datetime-local", data_local_for: "vote-start-time-utc", min: current_date_string(), value: format_datetime(input_value(f, :vote_start_time_local)) %>
    <%= error_tag f, :vote_start_time_local %>
  </div>

  <div class="form-group">
    <%= label f, :vote_end_time_local, "Voting End Time" %>
    <%= text_input f, :vote_end_time_local, class: "form-control convert-utc", type: "datetime-local", data_local_for: "vote-end-time-utc", min: current_date_string(), value: format_datetime(input_value(f, :vote_end_time_local))  %>
    <%= error_tag f, :vote_end_time_local %>
  </div>

  <input type="hidden" name="competition[vote_start_time_utc]" id="vote-start-time-utc" value="<%= input_value(f, :vote_start_time_utc) %>">

  <input type="hidden" name="competition[vote_end_time_utc]" id="vote-end-time-utc" value="<%= input_value(f, :vote_end_time_utc) %>">

  <%= submit "Update", class: "btn btn-primary pull-right" %>
<% end %>